# Generated by Django 4.2.28 on 2026-03-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RESERVIST', 'Reservist'), ('CDC', 'Civilian Defense Corps'), ('RCDG', 'Regional Community Defense Group'), ('RESCOM', 'Reserve Command (Administrator)'), ('PDRRMO', 'Provincial DRRMO'), ('MDRRMO', 'Municipal DRRMO')], default='RESERVIST', max_length=20),
        ),
    ]
