# Generated by Django 4.2.28 on 2026-03-02 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_cdc',
            field=models.ForeignKey(blank=True, help_text='The CDC this user belongs to', limit_choices_to={'role': 'CDC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdc_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_rcdg',
            field=models.ForeignKey(blank=True, help_text='The RCDG this user belongs to', limit_choices_to={'role': 'RCDG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rcdg_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Reservists default to False until CDC approves them'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RESERVIST', 'Reservist'), ('CDC', 'Community Defense Center'), ('RCDG', 'Regional Community Defense Group'), ('RESCOM', 'Reserve Command (Administrator)'), ('PDRRMO', 'Provincial DRRMO'), ('MDRRMO', 'Municipal DRRMO')], default='RESERVIST', max_length=20),
        ),
    ]
