# Generated by Django 4.2.28 on 2026-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_assigned_cdc_user_assigned_rcdg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
