# Generated by Django 4.2.28 on 2026-03-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service_number',
        ),
        migrations.AddField(
            model_name='user',
            name='afpsn',
            field=models.CharField(blank=True, max_length=100, verbose_name='AFPSN'),
        ),
    ]
