# Generated by Django 4.2.28 on 2026-03-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_rcdg_cdc'),
        ('users', '0006_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_cdc',
            field=models.ForeignKey(blank=True, help_text='The CDC this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='references.cdc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_rcdg',
            field=models.ForeignKey(blank=True, help_text='The RCDG this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='references.rcdg'),
        ),
    ]
