# Generated by Django 4.2.28 on 2026-03-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_assigned_cdc_alter_user_assigned_rcdg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
    ]
