# Generated by Django 4.2.28 on 2026-03-04 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('CREATE_INCIDENT', 'Submitted Incident'), ('EDIT_INCIDENT', 'Edited Incident'), ('DELETE_INCIDENT', 'Deleted Incident'), ('RESTORE_INCIDENT', 'Restored Incident')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
