# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0003_rcdg_cdc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('muster_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musters', to='references.cdc')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_musters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Musters',
                'ordering': ['-muster_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusterEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='ENROLLED', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('muster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cdc_portal.muster')),
                ('reservist', models.ForeignKey(limit_choices_to={'role': 'RESERVIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='muster_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Muster enrollments',
                'ordering': ['muster', 'reservist__full_name'],
                'unique_together': {('muster', 'reservist')},
            },
        ),
    ]
