# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdc_portal', '0001_muster_and_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muster',
            name='location',
            field=models.CharField(
                blank=True,
                choices=[('Online', 'Online'), ('Face to Face', 'Face to Face')],
                max_length=50,
            ),
        ),
    ]
