# Generated by Django 4.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdc_portal', '0002_muster_location_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muster',
            old_name='description',
            new_name='activities',
        ),
        migrations.RemoveField(
            model_name='muster',
            name='status',
        ),
    ]
