# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdc_portal', '0003_remove_status_rename_description_to_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterenrollment',
            name='latitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text='Reservist location when marking present',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='musterenrollment',
            name='longitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text='Reservist location when marking present',
                max_digits=10,
                null=True,
            ),
        ),
    ]
