# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdc_portal', '0004_musterenrollment_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusterNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('muster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cdc_portal.muster')),
                ('reservist', models.ForeignKey(limit_choices_to={'role': 'RESERVIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='muster_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Muster notifications',
                'ordering': ['-created_at'],
                'unique_together': {('reservist', 'muster')},
            },
        ),
    ]
