# Generated by Django 4.2.28 on 2026-03-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservist_portal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
