# Generated by Django 4.2.28 on 2026-03-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'City / Municipality',
                'verbose_name_plural': 'Cities / Municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('name', 'region')},
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.AddField(
            model_name='citymunicipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_municipalities', to='references.province'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='city_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='references.citymunicipality'),
        ),
        migrations.AlterUniqueTogether(
            name='citymunicipality',
            unique_together={('name', 'province')},
        ),
        migrations.AlterUniqueTogether(
            name='barangay',
            unique_together={('name', 'city_municipality')},
        ),
    ]
