# Generated by Django 4.2.28 on 2026-03-03 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_barangay_citymunicipality_alter_region_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcdg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcdg_desc', models.CharField(max_length=20, unique=True)),
                ('rcdg_address', models.CharField(max_length=200)),
                ('rcdg_commander', models.CharField(max_length=100)),
                ('cp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('time_encoded', models.TimeField(auto_now_add=True)),
                ('date_encoded', models.DateField(auto_now_add=True)),
                ('time_updated', models.TimeField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'RCDG',
            },
        ),
        migrations.CreateModel(
            name='Cdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdc_code', models.CharField(max_length=20, unique=True)),
                ('cdc_desc', models.CharField(max_length=60, null=True, unique=True)),
                ('cdc_address', models.CharField(max_length=200, null=True)),
                ('cdc_director', models.CharField(max_length=100, null=True)),
                ('cp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('time_encoded', models.TimeField(auto_now_add=True)),
                ('date_encoded', models.DateField(auto_now_add=True)),
                ('time_updated', models.TimeField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('rcdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.rcdg')),
            ],
            options={
                'verbose_name_plural': 'CDC',
            },
        ),
    ]
