# Generated by Django 4.2.28 on 2026-03-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_rcdg_cdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_code', models.CharField(max_length=20, unique=True)),
                ('rank_desc', models.CharField(max_length=255)),
                ('time_encoded', models.TimeField(auto_now_add=True)),
                ('date_encoded', models.DateField(auto_now_add=True)),
                ('time_updated', models.TimeField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ranks',
                'ordering': ['rank_code'],
            },
        ),
    ]
