# Generated by Django 4.2.28 on 2026-03-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_add_rank_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_code', models.CharField(default='TARGET', max_length=50)),
                ('name_desc', models.CharField(default='TARGET — Emergency Tracker', max_length=255)),
            ],
            options={
                'verbose_name': 'App Branding',
                'verbose_name_plural': 'App Branding',
            },
        ),
    ]
