# Generated by Django 4.2.28 on 2026-03-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservist_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reservist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
