# Generated by Django 4.2.28 on 2026-03-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservist_portal', '0003_incident_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
