# Generated by Django 4.2.28 on 2026-03-04 13:48

import django.core.validators
from django.db import migrations, models
import reservist_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservist_portal', '0004_incident_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload video or image evidence (max 100MB)', null=True, upload_to=reservist_portal.models.incident_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'wmv', 'webm', 'jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
