# Generated by Django 4.2.28 on 2026-03-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservist_portal', '0005_alter_incident_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('accident', 'Accident'), ('earthquake', 'Earthquake'), ('flood', 'Flood'), ('typhoon', 'Typhoon'), ('fire', 'Fire'), ('landslide', 'Landslide'), ('others', 'Others')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20),
        ),
    ]
