# Generated by Django 4.2.29 on 2026-03-06 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservist_portal', '0006_alter_incident_incident_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('responding', 'Responding'), ('on_scene', 'On Scene'), ('completed', 'Completed')], default='available', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='reservist_portal.incident')),
                ('reservist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('reservist', 'incident')},
            },
        ),
    ]
